// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/ArcadeDriveWithInputs.h"
#include "Commands/ArcadeDriveWithJoysticks.h"
#include "Commands/Auton0DoNothing.h"
#include "Commands/Auton1MobilityBonus.h"
#include "Commands/Auton2BlindShot.h"
#include "Commands/Auton3DoubleBlindShot.h"
#include "Commands/Auton4LowGoal.h"
#include "Commands/Auton5HotGoal.h"
#include "Commands/Auton6DoubleHotGoal.h"
#include "Commands/Auton6DoubleHotGoalSANE.h"
#include "Commands/Auton6PartialStartCold.h"
#include "Commands/Auton6PartialStartHot.h"
#include "Commands/Delay.h"
#include "Commands/DriveForDistance.h"
#include "Commands/DriveToAngle.h"
#include "Commands/MoveArmIn.h"
#include "Commands/MoveArmOut.h"
#include "Commands/ReleaseLatch.h"
#include "Commands/RunRollerBar.h"
#include "Commands/RunRollerBarBackwards.h"
#include "Commands/ShiftToHighGear.h"
#include "Commands/Shoot.h"
#include "Commands/TensionLauncher.h"
#include "Commands/UnwindWinch.h"
#include "Commands/WaitForHotGoal.h"
#include "Commands/WinchLauncherDown.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	gamepad = new Joystick(3);
	
	releaseLatchOverride = new JoystickButton(gamepad, 11);
	releaseLatchOverride->WhenPressed(new ReleaseLatch());
	shootAndReload = new JoystickButton(gamepad, 8);
	shootAndReload->WhenPressed(new Shoot());
	intakeWheelsBackwards = new JoystickButton(gamepad, 5);
	intakeWheelsBackwards->WhileHeld(new RunRollerBarBackwards());
	intakeWheelsForward = new JoystickButton(gamepad, 7);
	intakeWheelsForward->WhileHeld(new RunRollerBar());
	armOut = new JoystickButton(gamepad, 1);
	armOut->WhenPressed(new MoveArmOut());
	armIn = new JoystickButton(gamepad, 4);
	armIn->WhenPressed(new MoveArmIn());
	joystickRight = new Joystick(2);
	
	commandShiftButton = new JoystickButton(joystickRight, 1);
	commandShiftButton->WhileHeld(new ShiftToHighGear());
	joystickLeft = new Joystick(1);
	
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("ShiftToHighGear", new ShiftToHighGear());
	SmartDashboard::PutData("MoveArmOut", new MoveArmOut());
	SmartDashboard::PutData("WinchLauncherDown", new WinchLauncherDown());
	SmartDashboard::PutData("UnwindWinch", new UnwindWinch());
	SmartDashboard::PutData("ReleaseLatch", new ReleaseLatch());
	SmartDashboard::PutData("Shoot", new Shoot());
	SmartDashboard::PutData("Tension Launcher", new TensionLauncher());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	SmartDashboard::PutData("MoveArmIn", new MoveArmIn(true));
	
	windLauncherButton = new JoystickButton(gamepad, 9);
	windLauncherButton->WhileHeld(new WinchLauncherDown(true));
	unwindWinchButton = new JoystickButton(gamepad, 10);
	unwindWinchButton->WhileHeld(new UnwindWinch(true));
	tensionLauncherButton = new JoystickButton(gamepad, 3);
	tensionLauncherButton->ToggleWhenPressed(new TensionLauncher());
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getGamepad() {
	return gamepad;
}
Joystick* OI::getJoystickRight() {
	return joystickRight;
}
Joystick* OI::getJoystickLeft() {
	return joystickLeft;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
double OI::deadband(double input) {
	if (-0.05 < input && input < 0.05) {
		input = 0;
	}
	return input;
}
bool OI::shouldOverrideLatch() {
	return gamepad->GetRawButton(11) && gamepad->GetRawButton(12);
}
double OI::getForwardSpeed() {
	return -deadband(joystickLeft->GetY());
//	return joystickLeft->GetY();
}
double OI::getTurningSpeed() {
	return deadband(joystickRight->GetX());
//	return joystickRight->GetX();
}
