// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Robot.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION
Drivetrain* Robot::drivetrain = 0;
Arm* Robot::arm = 0;
Launcher* Robot::launcher = 0;
TheCompressor* Robot::theCompressor = 0;
OI* Robot::oi = 0;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION
void Robot::RobotInit() {
	RobotMap::init();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	drivetrain = new Drivetrain();
	arm = new Arm();
	launcher = new Launcher();
	theCompressor = new TheCompressor();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	// This MUST be here. If the OI creates Commands (which it very likely
	// will), constructing it during the construction of CommandBase (from
	// which commands extend), subsystems are not guaranteed to be
	// yet. Thus, their requires() statements may grab null pointers. Bad
	// news. Don't move it.
	oi = new OI();
	lw = LiveWindow::GetInstance();
	// instantiate the command used for the autonomous period
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
	autonomousCommand = new Auton0DoNothing();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
	
	autoChooser = new SendableChooser();
	autoChooser->AddDefault("0 - No Action", new Auton0DoNothing());
	autoChooser->AddObject("1 - Mobility Bonus", new Auton1MobilityBonus());
//	autoChooser->AddObject("2 - Low Goal, Mobility Bonus", /* tbd */);
//	autoChooser->AddObject("3 - High Goal, Mobility Bonus", /* tbd */);
//	autoChooser->AddObject("4 - Hot Goal, Mobility Bonus", /* tbd */);
//	autoChooser->AddObject("5 - High Goal, Hot Goal, Mobility Bonus", /* tbd */);
	SmartDashboard::PutData("Autonomous Routine",autoChooser);
}
	
void Robot::AutonomousInit() {
	autonomousCommand = (Command *)autoChooser->GetSelected();
	autonomousCommand->Start();
}
	
void Robot::AutonomousPeriodic() {
	Scheduler::GetInstance()->Run();
}
	
void Robot::TeleopInit() {
	// This makes sure that the autonomous stops running when
	// teleop starts running. If you want the autonomous to 
	// continue until interrupted by another command, remove
	// this line or comment it out.
	autonomousCommand->Cancel();
}
	
void Robot::TeleopPeriodic() {
	if (autonomousCommand != NULL)
		Scheduler::GetInstance()->Run();
}
void Robot::TestPeriodic() {
	lw->Run();
}
START_ROBOT_CLASS(Robot);
