// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ArcadeDriveWithInputs.h"
ArcadeDriveWithInputs::ArcadeDriveWithInputs(float forward, float turning, double time) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	forwardSpeed = forward;
	turningSpeed = turning;
	timeoutTime = time;
	if (timeoutTime > 0) {
		SetTimeout(timeoutTime);
	}
}
// Called just before this Command runs the first time
void ArcadeDriveWithInputs::Initialize() {
	printf("Driving with inputs...\n");
}
// Called repeatedly when this Command is scheduled to run
void ArcadeDriveWithInputs::Execute() {
	Robot::drivetrain->ArcadeDriveWithParameters(forwardSpeed,turningSpeed);
}
// Make this return true when this Command no longer needs to run execute()
bool ArcadeDriveWithInputs::IsFinished() {
	if (timeoutTime > 0) {
		return IsTimedOut();
	} else {
		return false;
	}
}
// Called once after isFinished returns true
void ArcadeDriveWithInputs::End() {
	Robot::drivetrain->ArcadeDriveWithParameters(0,0);
	printf("Done driving with inputs.\n\n");
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ArcadeDriveWithInputs::Interrupted() {
	End();
}
