// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.



#include "Auton3DoubleBlindShot.h"

#include "Commands.h"

Auton3DoubleBlindShot::Auton3DoubleBlindShot() {
	// Add Commands here:
	// e.g. AddSequential(new Command1());
	//      AddSequential(new Command2());
	// these will run in order.

	// To run multiple commands at the same time,
	// use AddParallel()
	// e.g. AddParallel(new Command1());
	//      AddSequential(new Command2());
	// Command1 and Command2 will run in parallel.

	// A command group will require all of the subsystems that each member
	// would require.
	// e.g. if Command1 requires chassis, and Command2 requires arm,
	// a CommandGroup containing them would require both the chassis and the
	// arm.
	
//	AddSequential(new Shoot(),3);
//	
//	if (Robot::launcher->IsShooterArmDown() && Robot::launcher->IsWinchUp()) {
//		AddSequential(new RunRollerBar(),3); // on failure, we need to drive forward
//		if (true /* !isThereABall */) {
//			AddSequential(new Shoot(),3);
//		}
//	}
//	
//	AddSequential(new DriveForDistance(4)); // could do this with time delay
	
	AddSequential(new MoveArmOut());
	
	AddSequential(new WinchLauncherDown());
	
	AddSequential(new UnwindWinch());
	
	AddSequential(new ReleaseLatch());
	
	AddSequential(new WinchLauncherDown());
	
	AddParallel(new RunRollerBar());
	AddSequential(new UnwindWinch());
	
	AddParallel(new RunRollerBar());
	AddSequential(new Delay(1)); // To make sure the ball gets in
//	AddSequential(new WaitForBall());
	
	AddSequential(new ReleaseLatch());
	
	AddSequential(new WinchLauncherDown());
	
	AddSequential(new UnwindWinch());

}
