// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RunRollerBar.h"
RunRollerBar::RunRollerBar(double timeout) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	if (timeout != 0) {
		SetTimeout(timeout);
	} else {
		SetTimeout(5);
	}
}
// Called just before this Command runs the first time
void RunRollerBar::Initialize() {
	printf("Running the roller bar...\n");
}
// Called repeatedly when this Command is scheduled to run
void RunRollerBar::Execute() {
	Robot::arm->RunRollerBarAtSpeed(1);
}
// Make this return true when this Command no longer needs to run execute()
bool RunRollerBar::IsFinished() {
	return IsTimedOut();
}
// Called once after isFinished returns true
void RunRollerBar::End() {
	Robot::arm->RunRollerBarAtSpeed(0);
	printf("Done running the roller bar.\n\n");
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void RunRollerBar::Interrupted() {
	End();
}
