// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.



#include "Shoot.h"

#include "WinchLauncherDown.h"
#include "UnwindWinch.h"
#include "ReleaseLatch.h"
#include "MoveArmOut.h"
#include "Delay.h"

Shoot::Shoot() {
	// Add Commands here:
	// e.g. AddSequential(new Command1());
	//      AddSequential(new Command2());
	// these will run in order.

	// To run multiple commands at the same time,
	// use AddParallel()
	// e.g. AddParallel(new Command1());
	//      AddSequential(new Command2());
	// Command1 and Command2 will run in parallel.

	// A command group will require all of the subsystems that each member
	// would require.
	// e.g. if Command1 requires chassis, and Command2 requires arm,
	// a CommandGroup containing them would require both the chassis and the
	// arm.
	
	AddSequential(new MoveArmOut());
	AddSequential(new WinchLauncherDown());
	AddSequential(new UnwindWinch());
	AddSequential(new ReleaseLatch());
	AddSequential(new WinchLauncherDown());
	AddSequential(new UnwindWinch());
/*
	AddSequential(new MoveArmOut());
	printf("I just moved the arm out\n");
	
	if (Robot::arm->IsArmOut()){
		printf("The arm is out, so I'm gonna check the winch\n");
		if (!Robot::launcher->IsShooterArmDown()) {
			AddSequential(new WinchLauncherDown());
			printf("The winch wasn't down, so I scheduled that\n");
		}
		if (!Robot::launcher->IsWinchUp()) {
			AddSequential(new UnwindWinch());
			printf("The winch wasn't unwound, so I fixed that\n");
		}
		//Actually shoot
		printf("Everything looks good, let's shoot!\n");
		if (Robot::arm->IsArmOut()) {
			printf("I just checked one more time that the arm was out\n");
			AddSequential(new ReleaseLatch());
			printf("Released!\n");
			AddSequential(new Delay(2));
		}
		//Prepare for next shot
		printf("Okay, time to prepare the next shot\n");
		if (Robot::arm->IsArmOut()) {
			printf("The arm was out, so I can do the winch stuff\n");
			AddSequential(new WinchLauncherDown());
			AddSequential(new UnwindWinch());
		} else {
			printf("Gotta move the arm out first though...\n");
			AddSequential(new MoveArmOut());
		}
		printf("Let's do the winch stuff one more time to make sure...\n");
		AddSequential(new WinchLauncherDown());
		AddSequential(new UnwindWinch());
	}
	printf("Done!\n");
*/
}
